### ISSUE TITLE
sublist中8号抓取不完全

### ISSUE THREAD

**Issue by WAWXuan** [alanbobs999/TopFreeProxies#14]
/sub/list/08.txt只有trojan

    "id": 8,
    "remarks": "ssrsub/ssr",
    "url": "https://raw.githubusercontent.com/ssrsub/ssr/master/V2Ray|https://raw.githubusercontent.com/ssrsub/ssr/master/ss-sub|https://raw.githubusercontent.com/ssrsub/ssr/master/ssrsub|https://raw.githubusercontent.com/ssrsub/ssr/master/trojan",
    "enabled": true

**Comment by alanbobs999** [comment]
是因为所有三个链接的内容都被第三个链接覆盖了，已经修复。
