### ISSUE TITLE
手机直接导入clash订阅链接不能使用？

### ISSUE THREAD

**Issue by AutismYu** [alanbobs999/TopFreeProxies#17]
手机端clash直接导入https://raw.fastgit.org/alanbobs999/TopFreeProxies/master/Eternity.yml  ， 保存后不能下载配置文件。
电脑端可以正常使用

显示如下错误

![Screenshot_20220310_160703_com github kr328 clash foss](https://user-images.githubusercontent.com/72010336/157616464-ca5c07eb-8d9e-45ae-a1c8-556869c4b9c4.png)

**Comment by alanbobs999** [comment]
客户端是什么？Clash For Android 测试正常。

**Comment by AutismYu** [comment]
我用的就是Clash for Android 2.5.4.foss  
我的步骤如下：配置-“+”-URL-输入订阅链接-保存
但是保存不了，说是rule-set不支持是怎么回事呢

**Comment by alanbobs999** [comment]
哦，进程相关的分流规则需要 Clash Premium 内核。可以到 https://github.com/Kr328/ClashForAndroid/releases 下载文件名有 premium 的。

**Comment by AutismYu** [comment]
已经可以使用了，非常感谢你的解答
