### ISSUE TITLE
无法导入/更新

### ISSUE THREAD

**Issue by Hexrotor** [alanbobs999/TopFreeProxies#18]
在Android 8 & 10 设备上测试均无法导入/更新，之前可以。
应用: Clash for Android Premium 2.5.4(以及2.5.5)
报错: 
![IMG_20220328_210726](https://user-images.githubusercontent.com/45112661/160404988-58b458b8-01c7-42b2-a01e-d57d39224e71.jpg)

**Comment by Hexrotor** [comment]
奇怪了，同一台设备，一会儿不报错一会儿报错。不是网络原因，我把yml文件下载后手动导入也报错

**Comment by alanbobs999** [comment]
应该是我自己写的转换程序出现了问题，现在已经转为使用 subconverter 进行转换。
