### ISSUE TITLE
clash客户端怎么使用？

### ISSUE THREAD

**Issue by lambdawt** [alanbobs999/TopFreeProxies#19]
是下载update/provider文件夹下的任意yml文件，然后再clash的profiles中import进去吗？这样会提示错误

**Comment by alanbobs999** [comment]
应该下载根目录的 Eternity.yml ，也可以在 README 里复制订阅链接导入，这样不需要手动下载。

**Comment by lambdawt** [comment]
谢谢，但不知道哪里出了问题，复制链接download后，提示Error：Network Error

**Comment by ZWXAllen** [comment]
你估计复制错了吧？地址是：https://raw.githubusercontent.com/alanbobs999/TopFreeProxies/master/Eternity.yml，如果你打不开就用国内加速节点：https://github-do.panbaidu.cn/https://raw.githubusercontent.com/alanbobs999/TopFreeProxies/master/Eternity.yml

**Comment by lambdawt** [comment]
> 你估计复制错了吧？地址是： https://raw.githubusercontent.com/alanbobs999/TopFreeProxies/master/Eternity.yml 如果你打不开就用国内加速节点： https://github-do.panbaidu.cn/https://raw.githubusercontent.com/alanbobs999/TopFreeProxies/master/Eternity.yml

后面那个国内加速节点成功了，谢谢！
