### ISSUE TITLE
小火箭无法获取更新

### ISSUE THREAD

**Issue by oscarwty** [alanbobs999/TopFreeProxies#22]
这两天小火箭点更新，弹出一个叉，”不能获取订阅节点”
（太快了我截不下来）
设备iPad Air2
系统版本15.4.1
小火箭版本2.2.4(1593)
试过上下两个clash链接都不行，开关全局代理都不行。
电脑的clash可以正常获取。

**Comment by alanbobs999** [comment]
小火箭不能用 Clash 配置的，导入 Base64 配置。

**Comment by oscarwty** [comment]
> 小火箭不能用 Clash 配置的，导入 Base64 配置。

感谢，已经可以了。
