### ISSUE TITLE
clash 无法导入，报错「did not find expected node content」

### ISSUE THREAD

**Issue by ArsenicX** [alanbobs999/TopFreeProxies#23]
感谢大佬的汇总，不知道为什么，clash无法导入，总是提示
```
Remote Config Format Error: yaml: line 52: did not find expected node content
```
尝试了国内链接也不行，用base64编码搭配地址转换工具也不行，下载yaml到本地也不行。
大佬能帮看下怎么回事吗？

**Comment by alanbobs999** [comment]
应该是节点名称为空产生的问题，已经更新节点了。

**Comment by WAWXuan** [comment]
> 应该是节点名称为空产生的问题，已经更新节点了。

问题仍然存在

**Comment by alanbobs999** [comment]
> > 应该是节点名称为空产生的问题，已经更新节点了。
> 
> 问题仍然存在

导入的是哪个链接？

**Comment by WAWXuan** [comment]
> 

报错为 yaml:line 282:did not find expected node content
链接是Eterniy转换后的
https://api.v1.mk/sub?target=clash&url=https%3A%2F%2Fraw.githubusercontent.com%2Falanbobs999%2FTopFreeProxies%2Fmaster%2FEternity&insert=false&config=https%3A%2F%2Fraw.githubusercontent.com%2FACL4SSR%2FACL4SSR%2Fmaster%2FClash%2Fconfig%2FACL4SSR_Online_Mini.ini&emoji=true&list=false&udp=true&tfo=false&expand=true&scv=false&fdn=false&sort=false&new_name=true

**Comment by alanbobs999** [comment]
使用 Clash For Windows v0.19.12 导入成功未报错。

**Comment by WAWXuan** [comment]
相同链接再次测试
Clash For Windows v0.19.13导入成功
Clash For Android v2.5.4导入失败，yaml:line 282:did not find expected node content

> 使用 Clash For Windows v0.19.12 导入成功未报错。

**Comment by ArsenicX** [comment]
我的设备是 ClashX v1.50.1.1，通过最新的链接 https://raw.githubusercontent.com/alanbobs999/TopFreeProxies/master/Eternity.yml 添加节点依旧报错：
```
Remote Config Format Error: yaml: line 276: did not find expected node content
```

**Comment by Vogadero** [comment]
> 我的设备是 ClashX v1.50.1.1，通过最新的链接 https://raw.githubusercontent.com/alanbobs999/TopFreeProxies/master/Eternity.yml 添加订阅依旧报错：
> ```
> Remote Config Format Error: yaml: line 276: did not find expected node content
> ```
> 

＋1，276行出错

**Comment by alanbobs999** [comment]
可能原因是节点名称开头是冒号造成 YAML 解析错误，重命名节点后再测试一下。

**Comment by ArsenicX** [comment]
> 可能原因是节点名称开头是冒号造成 YAML 解析错误，重命名节点后再测试一下。

好像确实是这样。我把那几个名字是`:俄罗斯`的节点手动去掉之后就能更新了
如果大佬能优化一下这种带冒号名称的节点就好了

**Comment by alanbobs999** [comment]
> > 可能原因是节点名称开头是冒号造成 YAML 解析错误，重命名节点后再测试一下。
> 
> 好像确实是这样。我把那几个名字是`:俄罗斯`的节点手动去掉之后就能更新了 如果大佬能优化一下这种带冒号名称的节点就好了

以后重命名之后再上传发布。
