### ISSUE TITLE
节点格式化报错

### ISSUE THREAD

**Issue by 666greatChina888** [alanbobs999/TopFreeProxies#26]
- SSR节点在sub_convert.py中丢失对应信息，导致格式化错误

**Comment by alanbobs999** [comment]
目前 SSR 节点比较少，暂时没有做 SSR 配置转化。

**Comment by 666greatChina888** [comment]
OK，那我自己琢磨琢磨2😂

**Comment by 666greatChina888** [comment]
OK，那我自己琢磨琢磨2😂

**Comment by 666greatChina888** [comment]
OK，那我自己琢磨琢磨😂

**Comment by 666greatChina888** [comment]
OK，那我自己琢磨琢磨😂

**Comment by aiweilwf** [comment]
- {name: :俄罗斯-ssr-213.183.53.200:9031-可用-直连-仅支持俄罗斯联邦地区NF自制剧, server: 213.183.53.200, port: 9031, type: ss, cipher: aes-256-cfb, password: BwcAUZk8hUFAkDGN, udp: true}
  - {name: :俄罗斯-ssr-213.183.53.177:9020-可用-直连-仅支持俄罗斯联邦地区NF自制剧, server: 213.183.53.177, port: 9020, type: ss, cipher: aes-256-cfb, password: BNmAXXxAHYpTRdzu, udp: true}

name 后多了个：

**Comment by alanbobs999** [comment]
> * {name: :俄罗斯-ssr-213.183.53.200:9031-可用-直连-仅支持俄罗斯联邦地区NF自制剧, server: 213.183.53.200, port: 9031, type: ss, cipher: aes-256-cfb, password: BwcAUZk8hUFAkDGN, udp: true}
> * {name: :俄罗斯-ssr-213.183.53.177:9020-可用-直连-仅支持俄罗斯联邦地区NF自制剧, server: 213.183.53.177, port: 9020, type: ss, cipher: aes-256-cfb, password: BNmAXXxAHYpTRdzu, udp: true}
> 
> name 后多了个：

是的，节点名称不规范会造成 YAML 解析错误。但是我自己写的转换程序的确没有写 SSR 节点转化😂。

**Comment by alanbobs999** [comment]
> OK，那我自己琢磨琢磨😂

加油，我暂时没有造轮子的动力了😭，代码写的太烂，协议变化更新又太快。没时间维护只能使用 subconverter 进行订阅转换了。

**Comment by buiawpkgew1** [comment]
@alanbobs999 他不是说解决SSR问题了 你怎么不改?
