### ISSUE TITLE
关于GitHub Action的问题

### ISSUE THREAD

**Issue by yu-steven** [alanbobs999/TopFreeProxies#29]
谢谢你提供的脚本，我将你的脚本融合到我的仓库里，已进行节点搜集，不过Action在运行时会时不时出现一个问题，见下方其中一个Action链接
https://github.com/yu-steven/openit/runs/5964370725?check_suite_focus=true#step:8:16
这个问题是由python缓存引起的
这是什么问题呢，或者有什么解决办法吗？

**Comment by alanbobs999** [comment]
可以把缓存文件夹加入 .gitignore 中。具体原因我也不太清楚😂，本仓库 Action 运行没有发生过这个问题。

**Comment by yu-steven** [comment]
所以说缓存没有必要嘛

**Comment by alanbobs999** [comment]
> 所以说缓存没有必要嘛

对的。

**Comment by yu-steven** [comment]
> > 所以说缓存没有必要嘛
> 
> 对的。

好吧，不影响使用

**Comment by yu-steven** [comment]
又经过一晚上测试，发现没有再出现问题，谢谢🙏
