### ISSUE TITLE
关于./sub文件夹中的问题

### ISSUE THREAD

**Issue by yu-steven** [alanbobs999/TopFreeProxies#30]
兄弟，我一直想说那个sub文件夹里的base64文件是把下面的yaml文件编码了
是你疏忽了吗？还是特意的？
提醒你一下

**Comment by alanbobs999** [comment]
> 兄弟，我一直想说那个sub文件夹里的base64文件是把下面的yaml文件编码了
> 是你疏忽了吗？还是特意的？
> 提醒你一下

是疏忽😅，谢谢提醒。
