### ISSUE TITLE
对 ./utils/sub_convert.py 文件的补充

### ISSUE THREAD

**Issue by yu-steven** [alanbobs999/TopFreeProxies#32]
./utils/sub_convert.py 文件中的小国旗不完整
我指的是这里
https://github.com/alanbobs999/TopFreeProxies/blob/9fb4bc7920d3adbcfb883d473c43baf7882d02a9/utils/sub_convert.py#L274-L284
如果你想，我这里有补充内容，全部251个国家，按照A-Z排序；经过测试可以立即使用，你可以进入以下链接查看
https://github.com/yu-steven/openit/blob/23d9c0f5821c3833186bd44ebc2a10ddf5d3a742/utils/sub_convert.py#L293-L359

**Comment by alanbobs999** [comment]
好的，我会添加进去。
