### ISSUE TITLE
建议使用 https 类型的测速链接

### ISSUE THREAD

**Issue by staoran** [alanbobs999/TopFreeProxies#34]
大量的节点在访问 https 网站时网站都会报证书错误问题，http 网站访问正常，但是现在基本上都是 https 网站。在测试节点可用性时使用 http 类型的测速链接无法排除这些节点。使用 https 类型的测速链接可以排除这些节点。比如：https://connectivitycheck.gstatic.com/generate_204

**Comment by staoran** [comment]
谢谢，另外，最新生成的配置文件又开始报错了。
![image](https://user-images.githubusercontent.com/7844538/165103316-f41dd4a6-95ce-4511-b5d7-4fb39c82ae14.png)
![image](https://user-images.githubusercontent.com/7844538/165103469-3054f983-b58c-43a0-9785-f10aab3acbbf.png)

**Comment by alanbobs999** [comment]
是节点名称前的冒号导致的问题。一会重新筛选节点。
