### ISSUE TITLE
提一个过滤建议：速度检测

### ISSUE THREAD

**Issue by youlinstar** [alanbobs999/TopFreeProxies#41]
可以使用这个代理，然后测速，是否能在大陆连接到节点，并从大陆对节点进行速度检测，这样能过滤好多垃圾节点
我都是用的v2rayN里面的测速工具来过滤的
（虽然我有自己的节点，但是备用节点还是要继续测速的）
我看看有没有时间看下你的代码，如果有我这个就留着了，到时候提PR

**Comment by youlinstar** [comment]
![image](https://user-images.githubusercontent.com/94352609/167102181-52668e7f-229a-4649-8d7f-244a9fbcfa3a.png)
这是下午测的

**Comment by youlinstar** [comment]
> 之前手动测速也是用 v2rayN ，但是手动测速更新频率不能保证；我现在测速是在 GitHub 服务器用 Clash 设置代理（大陆节点），然后通过这个国内代理环境测速，但是目前的效果不太理想。

那我就先关了这个，到时候我看看有时间就搞一下

**Comment by buiawpkgew1** [comment]
为啥有很多节点不能用
