### ISSUE TITLE
问: convert_remote函数是干什么用的

### ISSUE THREAD

**Issue by yu-steven** [alanbobs999/TopFreeProxies#44]
函数`convert_remote`是干什么的呢，我在`list_merge.py`中发现的，blame中说是添加远程连接转换功能
https://github.com/alanbobs999/TopFreeProxies/blob/e03bec0dde4cf982e8c808addc400b7a33069f40/utils/list_merge.py#L30-L59
这个函数应该是`sub_convert.py`的这个部分
https://github.com/alanbobs999/TopFreeProxies/blob/e03bec0dde4cf982e8c808addc400b7a33069f40/utils/sub_convert.py#L650-L688
我发现它是去链接一个订阅转换网站，现有的订阅合并功能用到它了吗，我怕`https://api.v1.mk/`不稳定

**Comment by songtao1873** [comment]
GitHub action使用的外网环境，只要服务器不挂，其他问题不大，不过不用这个的话也是完全可以实现的。可能是版本迭代的遗留问题，看源码的话估计作者开发了挺久了。

**Comment by alanbobs999** [comment]
是的，现在是使用这个订阅转换服务合并节点的。使用它主要是因为我自己写的转换功能在转换某些节点时会造成信息丢失，也没太多时间维护😥。如果不在意节点信息丢失，可以使用本仓库的转换功能。

**Comment by alanbobs999** [comment]
> GitHub action使用的外网环境，只要服务器不挂，其他问题不大，不过不用这个的话也是完全可以实现的。可能是版本迭代的遗留问题，看源码的话估计作者开发了挺久了。

不是遗留问题，是我在写完转换功能之后加上的😥。是因为我自己写的订阅转换太烂了。

**Comment by songtao1873** [comment]
> GitHub action使用的外网环境，只要服务器不挂，其他问题不大，不过不用这个的话也是完全可以实现的。可能是版本迭代的遗留问题，看源码的话估计作者开发了挺久了。

此外如果不使用这个实现的话可能工作量会大好几倍，因为需要判断订阅链接是clash还是base64编码的，base64只需要decode一下就可以 ，但是clash订阅的话就麻烦了，需要做字符串替换等等工作，具体过程可以打个断点自己跑一下，字符串处理看的我头皮发麻

**Comment by yu-steven** [comment]
> > GitHub action使用的外网环境，只要服务器不挂，其他问题不大，不过不用这个的话也是完全可以实现的。可能是版本迭代的遗留问题，看源码的话估计作者开发了挺久了。
> 
> 不是遗留问题，是我在写完转换功能之后加上的😥。是因为我自己写的订阅转换太烂了。

但是现在的转换功能我看还是你的的代码啊

**Comment by songtao1873** [comment]
> > GitHub action使用的外网环境，只要服务器不挂，其他问题不大，不过不用这个的话也是完全可以实现的。可能是版本迭代的遗留问题，看源码的话估计作者开发了挺久了。
> 
> 不是遗留问题，是我在写完转换功能之后加上的😥。是因为我自己写的订阅转换太烂了。

clash转base64节点转麻了😂

**Comment by yu-steven** [comment]
https://github.com/alanbobs999/TopFreeProxies/blob/master/utils/list_merge.py#L61-L65
这部分我发现还是用你写的代码呐

**Comment by alanbobs999** [comment]
> https://github.com/alanbobs999/TopFreeProxies/blob/1819e91dfefa44a65b0a9bbb1bacb97fd91ff1cc/utils/list_merge.py#L61-L65
> 
> 这部分我发现还是用你写的代码呐 或者说在线的订阅转换和你写的代码是互补的关系吗，还是直接废弃了你的decode代码呢

对，我没有废弃。只有合并生成的 Clash 配置文件是使用我自己的代码，因为可以对节点重命名，更格式化一点。

**Comment by yu-steven** [comment]
OK，了解呐

**Comment by yu-steven** [comment]
这里提个小建议
建议把远程订阅转换服务塞进GitHub action里
这样就不怕你订阅转换gg后还要换
只要在GitHub action的[安装py步骤之后添加](https://github.com/alanbobs999/TopFreeProxies/actions/runs/2324054289/workflow#L19-L22)
```
    - name: 安装subconverter
      run: |
         wget https://github.com/yu-steven/subconverter/releases/download/v0.7.2/subconverter_linux64.tar.gz -O subconverter.tar.gz&&tar -zxvf subconverter.tar.gz&&nohup ./subconverter/subconverter &
```
这段代码，然后在
https://github.com/alanbobs999/TopFreeProxies/blob/e03bec0dde4cf982e8c808addc400b7a33069f40/utils/sub_convert.py#L650
中`host='https://api.v1.mk'`修改问 `host='http://0.0.0.0:25500'`即可

原理也好懂，就是把订阅转换服务放到了action里，在内部通过访问本机的25500端口(默认)进行转换就可以的啦

**Comment by songtao1873** [comment]
不错

**Comment by yu-steven** [comment]
> 不错

👀

**Comment by alanbobs999** [comment]
> 这里提个小建议，无关紧要 建议把远程订阅转换服务塞进GitHub action里 这样就不怕你订阅转换gg后还要换 只要在GitHub action的[安装py步骤之后添加](https://github.com/alanbobs999/TopFreeProxies/actions/runs/2324054289/workflow#L19-L22)
> 
> ```
>     - name: 安装subconverter
>       run: |
>          wget https://github.com/yu-steven/subconverter/releases/download/v0.7.2/subconverter_linux64.tar.gz -O subconverter.tar.gz&&tar -zxvf subconverter.tar.gz&&nohup ./subconverter/subconverter &
> ```
> 
> 这段代码，然后在
> 
> https://github.com/alanbobs999/TopFreeProxies/blob/e03bec0dde4cf982e8c808addc400b7a33069f40/utils/sub_convert.py#L650
> 
> 
> 中`host='https://api.v1.mk'`修改为`host='http://0.0.0.0:25500'`即可
> 原理也好懂，就是把订阅转换服务放到了action里，在内部通过访问本机的25500端口(默认)进行转换就可以的啦

我也是这样想的😂，已经加上了。

**Comment by yu-steven** [comment]
NICE 😂
