### ISSUE TITLE
out.json 哪里来的？

### ISSUE THREAD

**Issue by ykk648** [alanbobs999/TopFreeProxies#47]
我使用lite 测速 不会生成out.json文件

**Comment by ykk648** [comment]
测试了0.9.1版本可以生成json文件， 但是最新的0.10不可以，这有理由吗？

**Comment by ykk648** [comment]
搞定了  另外#26下面的ssr解析代码可用

**Comment by a2470982985** [comment]
hello out.json这个是哪里来的

**Comment by alanbobs999** [comment]
> hello out.json这个是哪里来的

https://github.com/xxf098/LiteSpeedTest/blob/6a2f1a7b17afc0249eab6b61d961bb67e3afce7a/web/profile.go#L420-L426

是我修改原作者代码实现的，[Fork 仓库链接](https://github.com/alanbobs999/LiteSpeedTest).
