### ISSUE TITLE
能否提高节点筛选、合并的频率？

### ISSUE THREAD

**Issue by zero-hugo** [alanbobs999/TopFreeProxies#48]
节点失效很快，一天筛选合并一次显得不大够，到了下午或者晚上，节点基本上都不能用了，或者速度很慢了。如果能一天多几次筛选，是否就能解决这个问题。

**Comment by buiawpkgew1** [comment]
@zero-hugo 你可以fork自己改

**Comment by zero-hugo** [comment]
> @zero-hugo 你可以fork自己改
我也想啊，可是不懂编程，实在不知道该怎么弄。

**Comment by zero-hugo** [comment]
> @zero-hugo 你可以fork自己改
你能教教我该在哪里修改相关参数吗？

**Comment by buiawpkgew1** [comment]
> > @zero-hugo 你可以fork自己改
> > 你能教教我该在哪里修改相关参数吗？

https://github.com/alanbobs999/TopFreeProxies/tree/master/.github/workflows

**Comment by zero-hugo** [comment]
> > > @zero-hugo 你可以fork自己改
> > > 你能教教我该在哪里修改相关参数吗？
> 
> https://github.com/alanbobs999/TopFreeProxies/tree/master/.github/workflows 2个自己改 ![image](https://user-images.githubusercontent.com/71136405/179648086-230fbdca-39da-40c0-9270-fc54c5e63a80.png)
谢谢，改了下，不知道对不对，改成了0 2,4,8,10,12,14这样子，应该是表示间隔两小时吧？

**Comment by buiawpkgew1** [comment]
> > > > @zero-hugo 你可以fork自己改
> > > > 你能教教我该在哪里修改相关参数吗？
> > 
> > 
> > [https://github.com/alanbobs999/TopFreeProxies/tree/master/.github/workflows](https://github.com/alanbobs999/TopFreeProxies/tree/master/.github/workflows?rgh-link-date=2022-07-19T02%3A28%3A48Z) 2个自己改 ![image](https://user-images.githubusercontent.com/71136405/179648086-230fbdca-39da-40c0-9270-fc54c5e63a80.png)
> > 谢谢，改了下，不知道对不对，改成了0 2,4,8,10,12,14这样子，应该是表示间隔两小时吧？

  你可以看看https://crontab.guru/

**Comment by zero-hugo** [comment]
> > > > > @zero-hugo 你可以fork自己改
> > > > > 你能教教我该在哪里修改相关参数吗？
> > > 
> > > 
> > > [https://github.com/alanbobs999/TopFreeProxies/tree/master/.github/workflows](https://github.com/alanbobs999/TopFreeProxies/tree/master/.github/workflows?rgh-link-date=2022-07-19T02%3A28%3A48Z) 2个自己改 ![image](https://user-images.githubusercontent.com/71136405/179648086-230fbdca-39da-40c0-9270-fc54c5e63a80.png)
> > > 谢谢，改了下，不知道对不对，改成了0 2,4,8,10,12,14这样子，应该是表示间隔两小时吧？
> 
> 你可以看看https://crontab.guru/

好的

**Comment by alanbobs999** [comment]
我觉得目前的频率已经足够了。

节点容易失效的主要原因在于测速筛选出的节点质量太低，这是 Actions 网络环境造成的，暂时没想到啥好的解决方法。

本地测速是一个解决方法，但我没有这个条件，你有条件可以参考 [ykk648](https://github.com/ykk648/TopFreeProxies) 。

**Comment by buiawpkgew1** [comment]
> 我觉得目前的频率已经足够了。
> 
> 节点容易失效的主要原因在于测速筛选出的节点质量太低，这是 Actions 网络环境造成的，暂时没想到啥好的解决方法。
> 
> 本地测速是一个解决方法，但我没有这个条件，你有条件可以参考 [ykk648](https://github.com/ykk648/TopFreeProxies) 。

Actions 网络环境是国外的 没办法

**Comment by alanbobs999** [comment]
> > 我觉得目前的频率已经足够了。
> > 节点容易失效的主要原因在于测速筛选出的节点质量太低，这是 Actions 网络环境造成的，暂时没想到啥好的解决方法。
> > 本地测速是一个解决方法，但我没有这个条件，你有条件可以参考 [ykk648](https://github.com/ykk648/TopFreeProxies) 。
> 
> Actions 网络环境是国外的 没办法

尝试在 Actions 服务器上用代理软件把网络代理到国内服务器上，但是没有效果。

**Comment by ykk648** [comment]
> 我觉得目前的频率已经足够了。
> 
> 节点容易失效的主要原因在于测速筛选出的节点质量太低，这是 Actions 网络环境造成的，暂时没想到啥好的解决方法。
> 
> 本地测速是一个解决方法，但我没有这个条件，你有条件可以参考 [ykk648](https://github.com/ykk648/TopFreeProxies) 。

对质量要求不高的情况下，一个配置文件能用一周差不多，直到完全不能用了，失效80-90%我才考虑本地重新测速

CN节点测速很容易前排但失效快，目前是分到单独一组规则基本不用
