### ISSUE TITLE
请问如何设置按国家筛选节点？

### ISSUE THREAD

**Issue by zero-hugo** [alanbobs999/TopFreeProxies#49]
比如我想排除美国节点，只要香港之类的亚洲地区节点来测速排序，不知道应该修改哪里的参数。

**Comment by buiawpkgew1** [comment]
你能学Python吗？

**Comment by alanbobs999** [comment]
暂时没有开发这个功能。

https://github.com/alanbobs999/TopFreeProxies/blob/ac278159addbb223a4a2abd1e5b9766ba50cb9d6/utils/sub_convert.py#L191

可以在这个函数增加相关地区筛选的功能，标 emhancement 了，有时间会添加相关功能。

**Comment by buiawpkgew1** [comment]
> 暂时没有开发这个功能。
> 
> https://github.com/alanbobs999/TopFreeProxies/blob/ac278159addbb223a4a2abd1e5b9766ba50cb9d6/utils/sub_convert.py#L191
> 
> 可以在这个函数增加相关地区筛选的功能，标 emhancement 了，有时间会添加相关功能。

建议给他个表示
