### ISSUE TITLE
订阅地址

### ISSUE THREAD

**Issue by liu7526539** [alanbobs999/TopFreeProxies#54]
请问怎么可以将高速节点转成一个订阅地址呢

**Comment by buiawpkgew1** [comment]
![image](https://user-images.githubusercontent.com/71136405/185528558-696d07a9-f4d5-4b04-b459-e2df63a01c96.png)
这2个都是

**Comment by alanbobs999** [comment]
README 里有链接，直接选择相应客户端复制就可以。
