### ISSUE TITLE
大佬指导下这个如何在本地部署呀

### ISSUE THREAD

**Issue by huaxinCLUB** [alanbobs999/TopFreeProxies#55]
### 好多节点通过GitHub actions测速完在本地还是不能使用

**Comment by alanbobs999** [comment]
clone 仓库到本地，然后执行 workflow 里的命令：

https://github.com/alanbobs999/TopFreeProxies/blob/97f9c4101830e066e9002c341e779e7735165d5a/.github/workflows/speedtest.yml#L36-L39
