### ISSUE TITLE
windows clash 无法切换到此配置

### ISSUE THREAD

**Issue by xiaoyetanQAZ** [alanbobs999/TopFreeProxies#60]
clash for windows v 0.19.29 下载https://fastly.jsdelivr.net/gh/alanbobs999/TopFreeProxies@master/Eternity.yml 是成功的，切换配置时报这个错，该怎么解决。
![image](https://user-images.githubusercontent.com/76525615/192077598-5dd368d5-0f7a-436c-a939-b113ee671850.png)

**Comment by alanbobs999** [comment]
Due to wrong rule provider behavior, now it has been fixed.
