### ISSUE TITLE
There are duplicate nodes among the nodes

### ISSUE THREAD

**Issue by net-warriors** [alanbobs999/TopFreeProxies#61]
Hello, don't be tired.  In the nodes in this address, there are many duplicate nodes that have not been deleted. I usually delete them with v2rayn (Source nodes: https://raw.githubusercontent.com/alanbobs999/TopFreeProxies/master/sub/sub_merge.txt) .

**Comment by alanbobs999** [comment]
I would like to add this feature in the future.
