### ISSUE TITLE
Clash yml file does not work in Android

### ISSUE THREAD

**Issue by net-warriors** [alanbobs999/TopFreeProxies#62]
https://raw.githubusercontent.com/alanbobs999/TopFreeProxies/master/sub/sub_merge_yaml.yml
dont work in android
https://github.com/alanbobs999/TopFreeProxies/blob/master/Eternity.yml
https://github.com/alanbobs999/TopFreeProxies/blob/master/update/provider/provider-all.yml
 dont work in clash android

**Comment by alanbobs999** [comment]
Can you provider more information?

**Comment by net-warriors** [comment]
> Clash yaml file does not work in android

Error: cipher not supported
