### ISSUE TITLE
Rename nodes

### ISSUE THREAD

**Issue by net-warriors** [alanbobs999/TopFreeProxies#63]
Please, based on the location of the servers, change the name of the servers to the flag of the country and the abbreviation of the country's name(example: canada :: CA , german: DE). This way, your work will be more professional. I already did this for ss configuration, but I don't know how to do it for the rest( with ip api)
thankyou very very much

**Comment by alanbobs999** [comment]
I'm confused with your expresion. Do you mean that the name should be as `$flag$code$number` ? I'm now working on adding more customized featrues.

**Comment by net-warriors** [comment]
Yes '
Deleting previous names and setting new names will make your work
professional
