### ISSUE TITLE
无法添加至clashx pro

### ISSUE THREAD

**Issue by scientificworld** [alanbobs999/TopFreeProxies#65]
在添加托管配置 `https://fastly.jsdelivr.net/gh/alanbobs999/TopFreeProxies@master/Eternity.yml` 时，提示：

```
托管配置文件格式不正确: proxy 39: key 'password' missing
```

**Comment by alanbobs999** [comment]
是 Trojan 节点中 password 值为 null 的原因，可以暂时使用订阅转换工具转换 Base64 格式订阅使用。
