### ISSUE TITLE
Clash for Android订阅链接报错

### ISSUE THREAD

**Issue by martin2384798** [alanbobs999/TopFreeProxies#67]
错误信息截图：
![2944d6a39fffe4d1295a480aa28fbab](https://user-images.githubusercontent.com/12695319/194707817-55813d9e-f797-4167-8244-e35f9366f50f.jpg)

设备：小米6 MIUI 12 20.6.18
Clash版本：2.5.11.foss

复现步骤：
1.在配置中输入订阅链接（原生和国内加速都可）
2.点击保存，报错

**Comment by alanbobs999** [comment]
使用 premium 版本
