### ISSUE TITLE
Clash链接不能用，提示Initial local provider sg: file must have a `proxies` field

### ISSUE THREAD

**Issue by aliveday** [alanbobs999/TopFreeProxies#7]
小火箭不识别，Clash for android 导入最后校验失败，提示 Initial local provider sg: file must have a `proxies` field，config.yaml里面proxies是空的啊。

**Comment by alanbobs999** [comment]
这是由于没有sg节点但provider里还是载入造成的，会尽快修复。

**Comment by aliveday** [comment]
好的，谢谢。
无配置节点链接很容易被忽略，建议给换个更显眼的名字和位置。

**Comment by alanbobs999** [comment]
已经改为不使用 provider 了。

**Comment by aliveday** [comment]
> 已经改为不使用 provider 了。

额，能用就好，辛苦了。

**Comment by alanbobs999** [comment]
> > 已经改为不使用 provider 了。
> 
> 额，能用就好，辛苦了。 推荐一下苹果商店有个叫oneclick的免费软件，我没换小火箭之前一直用这个。

早想改成这样了，provider 如果碰上网络问题真是噩梦，我会考虑加入的。
