### ISSUE TITLE
Clash节点，没一个能用的！

### ISSUE THREAD

**Issue by micenote** [alanbobs999/TopFreeProxies#73]
Clash节点，没一个能用的！

**Comment by alanbobs999** [comment]
😥，测速是在 GitHub 服务器环境中进行的，很大概率会出现这种极端情况。
如果可以的话，你可以 Clone 本仓库到本地进行测速，这样更容易筛选出可用的节点。

**Comment by mahaisong** [comment]
> 

开完会，急什么

**Comment by alanbobs999** [comment]
影响速度的因素主要有节点来源的质量和有效的筛选，但现在的筛选效果并不是很好。

**Comment by alanbobs999** [comment]
> 首先感谢作者！
> 
> 坐标上海，速度我觉得ok，有个问题： 以前比较稳定，但是近期开始经常出现断流，比如视频播着就断了，等一小段时间刷新网页会恢复，不知道是否最近的提交导致，比较影响体验

这个是节点质量有问题，但用 Litespeedtest 比较难排除。

**Comment by ykk648** [comment]
@zptan 这份代码是靠本地手动更新的，我有了别的节点来源，所以这里没有更新了

**Comment by alanbobs999** [comment]
> @ykk648 好的，那 https://github.com/ykk648/TopFreeProxies 不会继续维护了是吗？

我推荐将仓库 clone 到本地然后在本地进行测速操作，修改 `main.py` 里的一些运行参数即可，这样的话筛选出的节点是最符合你的网络环境的。
如果不想生成订阅链接上传 Github 的话，可以将测速生成的文件直接覆盖 cfw 的配置文件，配合自动化脚本，可以实现自动更新的效果。

**Comment by ykk648** [comment]
@zptan 节点更新了，建议你拉到本地自己更新使用 :smile:

**Comment by alanbobs999** [comment]
> 3Q, @ykk648 @alanbobs999
> 
> 问下要覆盖哪些配置文件，是否可以在README里说明一下(比如环境的要求，例如`Python`要求什么版本，路径有什么要求，生成的文件有哪些，怎么用，etc)，这个需求应该是比较common的

配置文件是 `./utils/config.ini` ，依赖在 `requirement.txt` 中，有时间我会添加更详细的文档介绍。

**Comment by Lukeehujt** [comment]
我系统ubuntu22.04,内核版本5.15.0-52-generic，用firefox浏览器，使用clash代理，在本地仓库更新节点后，每天能有大概10个快速节点，但是使用clash自动选择节点时候，会有firefox报错PR_END_OF_FILE_ERROR,无法使用的情况，经过我查资料应该是无法跟服务器端建立安全的SSL连接，请问这种如何处理？能否在筛选节点时候筛掉这种高速但是无效的节点，或者有没有什么办法跟服务器建立安全连接？谢谢你的解答。

**Comment by alanbobs999** [comment]
> 我系统ubuntu22.04,内核版本5.15.0-52-generic，用firefox浏览器，使用clash代理，在本地仓库更新节点后，每天能有大概10个快速节点，但是使用clash自动选择节点时候，会有firefox报错PR_END_OF_FILE_ERROR,无法使用的情况，经过我查资料应该是无法跟服务器端建立安全的SSL连接，请问这种如何处理？能否在筛选节点时候筛掉这种高速但是无效的节点，或者有没有什么办法跟服务器建立安全连接？谢谢你的解答。

这种无法使用 Litespeedtest 筛选，暂时我也没有其它的解决方法。

**Comment by zero-hugo** [comment]
我也是一个节点能用的都没有。以前筛选出来都是美国节点的时候，更新过那段时间还能用，速度也挺快。现在有了很多亚洲节点，然后一个能用的都没有，都连不上的。

**Comment by alanbobs999** [comment]
> 我也是一个节点能用的都没有。以前筛选出来都是美国节点的时候，更新过那段时间还能用，速度也挺快。现在有了很多亚洲节点，然后一个能用的都没有，都连不上的。

我再测试一下，可能得改回去 :( 。因为之前能用的大部分都是亚洲节点，所以特意分开筛选了。
