### ISSUE TITLE
Yaml file error in Android

### ISSUE THREAD

**Issue by net-warriors** [alanbobs999/TopFreeProxies#75]
When we add the yaml file with a link to Clash in Android, it gives the message <<proxy 3471: TLS must be true with h2/grpc network>>

**Comment by alanbobs999** [comment]
Maybe it's a Subconverter issue, this repo uses Subconverter to convert subscriptions now.

**Comment by net-warriors** [comment]
Don't fix this error ! :   
https://raw.githubusercontent.com/alanbobs999/TopFreeProxies/master/sub/sub_merge_clash.yaml

**Comment by alanbobs999** [comment]
I can't reproduce this problem, and I have no solution for this problem yet, because it's a Subconverter issue. Maybe you should add this issue in [Subconverter repo](https://github.com/tindy2013/subconverter).
