### ISSUE TITLE
Editing server names

### ISSUE THREAD

**Issue by net-warriors** [alanbobs999/TopFreeProxies#76]
Please change the name of the servers to the flag- country and the number to make your work more professional
example: 
trojan://94a08db5-db61-487a-b208-c66445f32737@1024tw01.tfzhc.top:443?security=tls&sni=1024tw01.tfzhc.top&type=tcp&headerType=none#%F0%9F%87%A8%F0%9F%87%B3%201%7Ctg%E9%A2%91%E9%81%93%40ripaojiedian

convert to :
trojan://94a08db5-db61-487a-b208-c66445f32737@1024tw01.tfzhc.top:443?security=tls&sni=1024tw01.tfzhc.top&type=tcp&headerType=none#%F0%9F%87%A8%F0%9F%87%B3%20CN-1
 

OR

trojan://94a08db5-db61-487a-b208-c66445f32737@1024tw01.tfzhc.top:443?security=tls&sni=1024tw01.tfzhc.top&type=tcp&headerType=none#%F0%9F%87%A8%F0%9F%87%B3%20Chain-1

Or you can even show the name along with the location of the city and country to make it better, for example:

trojan://94a08db5-db61-487a-b208-c66445f32737@1024tw01.tfzhc.top:443?security=tls&sni=1024tw01.tfzhc.top&type=tcp&headerType=none#%F0%9F%87%A8%F0%9F%87%B3%20Chain-Hong Kong

**Comment by alanbobs999** [comment]
It's working in progress.

**Comment by net-warriors** [comment]
This is great
