### ISSUE TITLE
edit domain server to ip 

### ISSUE THREAD

**Issue by net-warriors** [alanbobs999/TopFreeProxies#77]
Please delete the duplicate servers and also change the domain name to IP. By doing this, you can delete the duplicate servers more easily.  Thank you very much

trojan://94a08db5-db61-487a-b208-c66445f32737@1024tw01.tfzhc.top:443?security=tls&sni=1024tw01.tfzhc.top&type=tcp&headerType=none#%F0%9F%87%B9%F0%9F%87%BC%20TW-1

convert to :

trojan://94a08db5-db61-487a-b208-c66445f32737@165.154.246.19:443?security=tls&sni=1024tw01.tfzhc.top&type=tcp&headerType=none#%F0%9F%87%B9%F0%9F%87%BC%20TW-1

**Comment by alanbobs999** [comment]
That's great! I will add this feature later.

**Comment by net-warriors** [comment]
Thank you my friend
