### ISSUE TITLE
Eternity.yml这个文件现在是3天还未更新，是不是里面节点也是3天未更新呢？

### ISSUE THREAD

**Issue by nietulong** [alanbobs999/TopFreeProxies#8]
如题，谢谢。

**Comment by nietulong** [comment]
> 是的。

这个文件更新的频率是多少，是自动更新的吗？

**Comment by alanbobs999** [comment]
> > 是的。
> 
> 这个文件更新的频率是多少，是自动更新的吗？

非自动不定期更新，通常有时间就会更新。

**Comment by nietulong** [comment]
> > > 是的。
> > 
> > 
> > 这个文件更新的频率是多少，是自动更新的吗？
> 
> 非自动不定期更新，通常有时间就会更新。

有没有办法弄成自动更新呢？

**Comment by alanbobs999** [comment]
我技术有限，现在暂时实现不了节点自动更新的功能。还有你说的更新是指的是客户端的更新订阅吗？

**Comment by nietulong** [comment]
我说的是Eternity.yml这个能不能自动更新，人工更新的话，你会很累的。你的项目跟这个很相似：https://github.com/ldir92664/Vmess-Actions，这里是实现啦自动更新




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月25日(星期四) 中午12:08
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [alanbobs999/TopFreeProxies] Eternity.yml这个文件现在是3天还未更新，是不是里面节点也是3天未更新呢？ (Issue #8)





 
我技术有限，现在暂时实现不了节点自动更新的功能。还有你说的更新是指的是客户端的更新订阅吗？

**Comment by nietulong** [comment]
> 我技术有限，现在暂时实现不了节点自动更新的功能。还有你说的更新是指的是客户端的更新订阅吗？

我说的是Eternity.yml这个能不能自动更新，人工更新的话，你会很累的。你的项目跟这个很相似：https://github.com/ldir92664/Vmess-Actions，这里是实现啦自动更新
