### ISSUE TITLE
help me 

### ISSUE THREAD

**Issue by net-warriors** [alanbobs999/TopFreeProxies#82]
I took a fork from your repository, when I run the action commands, the get proxies section gives an error: https://ibb.co/xjSpM5D

**Comment by alanbobs999** [comment]
Add `chmod +x ./utils/subconverter/subconverter-linux-amd64 && chmod +x ./utils/litespeedtest/lite-linux-amd64` commands before running main.py.
You can take a look at https://github.com/alanbobs999/TopFreeProxies/blob/2009419f6d435974158d5dfd9a634a7dea0fbc71/.github/workflows/get-proxies.yml#L35-L38 .
